feat: Make path overridable for startup probe and add timeoutSeconds property to all probe types
entur/helm-charts pull request #103
Opened 2023-06-15 11:49 UTC by nils1k

This pull request contains the following changes:

- It adds support for overriding the `path` and `port` properties for the startup probe
- It adds support for the `timeoutSeconds ` for all probe types
- It adds support for all timeout-related properties to the startup probe

2023-06-15 11:53 UTC, AlexanderBrevig commented
This is a very breaking change. We must support all our existing configs. Maybe only use http for startup if the  path is defined

2023-06-15 12:17 UTC, AlexanderBrevig requested changes

2023-06-15 12:17 UTC, AlexanderBrevig commented on charts/common/values-ci-tests.yaml
this file cannot change

2023-06-15 12:37 UTC, nils1k commented
> This is a very breaking change. We must support all our existing configs. Maybe only use http for startup if the path is defined

What would that look like in this case? Could we create the logic in the `_helpers.tpl` file, e.g.:

```yaml
startupProbe:
  tcpSocket:
    port: {{ .probes.startup.port | default .internalPort }}
  {{- if .probes.startup.path }}
  httpGet:
    path: {{ .probes.startup.path }}
    port: {{ .probes.startup.port | default .internalPort }}
  {{- end }}
```

Could another option be to let people add probes and their properties as they please with something like this in `deployment.yaml`: 

```yaml
{{- with .Values.probes -}}
```

and then simply define any probes under the following key in `values.yaml`:

```yaml
probes: {}
```

I think we would be able to keep backwards compatibility that way, or am I missing something?

2023-06-15 12:44 UTC, AlexanderBrevig commented
Thinking about it, you could already use [probes.spec](https://github.com/entur/helm-charts/blob/main/charts/common/tests/deployment_test.yaml#L438-L442)
```yaml
          probes:
            spec: # specify probes in accordance to k8s spec
              livenessProbe:
                tcpSocket:
                  port: admin
```

But to answer your question, the _helpers would look like this:
```yaml
startupProbe:
  {{- if .probes.startup.path }}
  httpGet:
    path: {{ .probes.startup.path }}
    port: {{ .probes.startup.port | default .internalPort }}
  {{- else }}
  tcpSocket:
    port: {{ .probes.startup.port | default .internalPort }}
  {{- end }}
```

2023-06-15 17:49 UTC, nils1k commented
> ```yaml
> probes.startup.path
> ```

Thanks! I've made some adjustments according to your suggestions, and added two more tests. Would you say the changes in this PR are really needed? My bad for not noticing the [probes.spec](https://github.com/entur/helm-charts/blob/main/charts/common/tests/deployment_test.yaml#L438-L442); we could use that to accomplish what we want.

2023-06-16 06:05 UTC, AlexanderBrevig commented
> [...] Would you say the changes in this PR are really needed?

I must honestly say that I do not. We should get some more opinions maybe? @Chr1stian @olsove @bvestli @sindrel. Took the liberty of tagging a few contributors :)

2023-06-16 06:42 UTC, Chr1stian commented
If this can be accomplished without changing the Chart, I dont see a need for it, but maybe document it just a little if others come looking for the same thing?

2023-06-16 06:47 UTC, bvestli commented
I agree with @AlexanderBrevig

2023-06-16 07:28 UTC, AlexanderBrevig commented
Thanks for the effort, but per discussion above this will not be part of "golden path" and an override of `probes.spec` will suffice.

2023-06-16 07:28 UTC, closed without merging

2023-06-16 07:35 UTC, nils1k commented
Sounds good 👍