feat: add pdb for sbx/dev/test envs + logic
entur/helm-charts pull request #109
Opened 2023-06-20 13:39 UTC by Glenn-Terjesen

2023-06-21 08:43 UTC, AlexanderBrevig commented
We should add some tests to prove the new functionality and make sure we don't accidentally regress.

2023-06-28 12:09 UTC, AlexanderBrevig requested changes
needs some unit tests to prove the change

2023-06-28 13:21 UTC, Glenn-Terjesen commented
@AlexanderBrevig added multiple tests, please take a look :-)

2023-06-28 19:40 UTC, AlexanderBrevig requested changes
Consider following the established pattern that when keys are redundant between the `deployment` stanza and `container`, they are prioritized for `deployment`.

`pdb.minAvailable > deployment.minAvailable > container.minAvailable`

2023-06-29 06:47 UTC, AlexanderBrevig requested changes

2023-06-29 06:47 UTC, AlexanderBrevig commented on charts/common/tests/pdb_test.yaml
> +        Replicas: 1
should be lower case

2023-06-29 09:07 UTC, AlexanderBrevig approved these changes
🎊

2023-06-29 11:55 UTC, merged