update doc
entur/helm-charts pull request #130
Opened 2023-10-04 12:14 UTC by Pavloro

2023-10-04 13:39 UTC, AlexanderBrevig commented on example/values-secrets.yaml
I think maybe we should add some top level description to README as well? And make the docs in values.yaml clearer so it get propagated to the chart documentation. What do you think?

2023-10-04 13:40 UTC, AlexanderBrevig requested changes
Moar cowbell (and more docs) 📜 ?

2023-10-05 08:27 UTC, Pavloro commented on example/values-secrets.yaml
I updated the documentation in Confluence. We can also add a README file in valuse.yaml, but then we need to update both files when changes come.

2023-10-06 11:55 UTC, AlexanderBrevig approved these changes

2023-10-06 11:55 UTC, AlexanderBrevig commented on .circleci/config.yml
move to GHA

2023-10-06 12:00 UTC, AlexanderBrevig approved these changes

2023-10-06 12:01 UTC, Pavloro commented
LGTM :+1:

2023-10-09 06:31 UTC, Glenn-Terjesen approved these changes

2023-10-09 06:32 UTC, merged