Set a default cpu-limit of 0.3. 0.1 is a bit too low.
entur/helm-charts pull request #57
Opened 2022-12-13 12:21 UTC by kagkarlsson

2022-12-20 13:49 UTC, torgeiou submitted a review, later dismissed

2023-01-09 07:08 UTC, AlexanderBrevig requested changes
This will defeat the default calculation of `cpuLimit` = `cpu * 5`

https://github.com/entur/helm-charts/blob/61b7f11e8086d34cad961b6f40b7447739cebfad/charts/common/templates/_helpers.tpl#L41-L45

2023-01-11 11:02 UTC, kagkarlsson commented
Hmm, there is no such calculated default limit for the postgres-container 🤔 

```
  resources:
    limits:
      {{- if .postgres.cpuLimit }}
      cpu: {{ .postgres.cpuLimit }}
      {{- else }}
      cpu: {{ .postgres.cpu }}
      {{- end }}
      memory: "{{ .postgres.memory }}Mi"
    requests:
      cpu: {{ .postgres.cpu }}
      memory: "{{ .postgres.memory }}Mi"
```

2023-01-11 11:47 UTC, AlexanderBrevig approved these changes
My bad, you are correct

2023-01-11 11:50 UTC, AlexanderBrevig approved these changes

2023-01-11 11:53 UTC, merged